version: '3.9'

services:
  active-user-exporter:
    build: .
    environment:
      - SPARK_APPLICATION_MAIN_CLASS=ir.sharif.math.story.PlayedTimeExporter
    networks:
      - overlay
#  active-user-in-course-exporter:
#    build: .
#    environment:
#      - SPARK_APPLICATION_MAIN_CLASS=ir.sharif.math.story.ActiveUsersInCourseExporter
#    networks:
#      - overlay

networks:
  overlay:
    external: true
    name: story-network
